#' Descriptive Tabulation and Chi-Square Test of Count Categories
#'
#' This function performs a descriptive tabulation of counts categorized into 
#' user-defined thresholds and compares the distribution across groups 
#' (e.g., instruments, runs, etc.) using a chi-square test. The function allows 
#' flexible filtering of data and returns both the chi-square p-value and a summary table.
#'
#' @param data A data frame containing the input data for tabulation and analysis.
#' @param comparison_column A string specifying the column to group by and compare 
#'   (e.g., `"Instrument"`, `"Run_ID"`).
#' @param count_column A string specifying the column with numeric count values 
#'   (default is `"count"`).
#' @param value_breaks A numeric vector defining the thresholds for categorizing counts. 
#'   Default is `c(150, 500, 2500)`.
#' @param filter_sample_type Optional. A string specifying a value of `sample_type` 
#'   to filter the data. Use `NULL` to skip filtering by `sample_type`.
#' @param filter_assay_type Optional. A string specifying a value of `assay_type` 
#'   to filter the data. Use `NULL` to skip filtering by `assay_type`.
#' @param filter_additional Optional. A string specifying a custom filter condition 
#'   (e.g., `"sample_qc == 'PASS'"` or `"count > 1000"`). Use `NULL` to skip additional filtering.
#'
#' @return A list with two elements:
#' \item{p_value}{The p-value from the chi-square test comparing the distribution 
#'   of count categories across groups. Very small p-values are displayed in scientific notation.}
#' \item{count_categ_table}{A summary table (generated by `gtsummary::tbl_summary`) 
#'   showing the distribution of count categories grouped by the specified `comparison_column`.}
#'
#' @examples
#' # Example with instruments
#' results <- descriptive_tabulation(
#'   data = both,
#'   comparison_column = "Instrument",
#'   count_column = "count",
#'   value_breaks = c(150, 500, 2500),
#'   filter_sample_type = "SAMPLE",
#'   filter_assay_type = "assay",
#'   filter_additional = "sample_qc == 'PASS'"
#' )
#' 
#' # Access the p-value and summary table
#' results$p_value
#' results$count_categ_table
#'
#' # Example with runs
#' results_runs <- descriptive_tabulation(
#'   data = both,
#'   comparison_column = "Run_ID",
#'   count_column = "count",
#'   value_breaks = c(100, 300, 1000),
#'   filter_sample_type = "SAMPLE",
#'   filter_assay_type = "assay"
#' )
#' 
#' results_runs$p_value
#' results_runs$count_categ_table
#'
#' @export
descriptive_tabulation


descriptive_tabulation <- function(data, 
                                   comparison_column, 
                                   count_column = "count", 
                                   value_breaks = c(150, 500, 2500), 
                                   filter_sample_type = NULL, 
                                   filter_assay_type = NULL, 
                                   filter_additional = NULL) {
  library(dplyr)
  library(gtsummary)
  
  # Apply filters to the data
  if (!is.null(filter_sample_type)) {
    data <- data %>% filter(sample_type == filter_sample_type)
  }
  if (!is.null(filter_assay_type)) {
    data <- data %>% filter(assay_type == filter_assay_type)
  }
  if (!is.null(filter_additional)) {
    data <- data %>% filter(!!rlang::parse_expr(filter_additional))
  }
  
  # Define the count categories based on the breaks
  count_labels <- c(
    paste0("Below", value_breaks[1]),
    paste0("Btw", value_breaks[1], "_", value_breaks[2]),
    paste0("Btw", value_breaks[2], "_", value_breaks[3]),
    paste0("Greater", value_breaks[3])
  )
  
  # Categorize counts
  data <- data %>%
    mutate(Count_Group = cut(
      !!sym(count_column),
      breaks = c(-Inf, value_breaks, Inf),
      labels = count_labels,
      right = FALSE
    )) %>%
    mutate(Count_Group = as.factor(Count_Group))
  
  # Chi-square test
  chisq_results <- chisq.test(data$Count_Group, data[[comparison_column]])
  
  # Handle very small p-values
  p_value <- ifelse(chisq_results$p.value < .Machine$double.eps, 
                    paste0("< ", format(.Machine$double.eps, scientific = TRUE)), 
                    chisq_results$p.value)
  
  # Tabulation summary
  count_categ_table <- data %>%
    select(Count_Group, !!sym(comparison_column)) %>%
    tbl_summary(by = !!sym(comparison_column))
  
  # Return results
  return(list(
    p_value = p_value,
    count_categ_table = count_categ_table
  ))
}
