input_data: "my_data.rds"          # Input data file path


parameters:
  Product: "ProjectA"
  Instrument: "instrumentB"
  run_var: "run_id"                      # Column for comparing
  Project: "Iteration runs Mars 2025"    # where does the data come from
  Background: "detection"  #eob var
  matrix_column: "matrix_name"
  npx_var: "pc_normalized_npx"

  

plot_settings:
 width: 10                              # Width of the plots
 height: 10                             # Height of the plots
 dpi: 300                               # DPI for plot saving
 fontsize: 14                           # text font size
 format: "png"                          # format of the figures


