library(segmented)
library(arrow)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(readr)  
library(npxexplorer)
library(OlinkAnalyze)
library(openxlsx)
library(gtsummary)
library(ggstatsplot)
library(ggridges)
library(statsExpressions)
library(viridis)
library("nloptr")
library("RColorBrewer")
library(ggpubr)
library(dplyr)
library(ggthemes)
library(ggside)
library(readxl)
library(knitr)
library(extrafont)
library(kableExtra)
library(readxl)
library(ggpubr)
library(gtsummary)
library(tidyverse)
library(ggfortify)
library(knitr)
library(extrafont)
library(kableExtra)
library(readxl)
library(ggpubr)
library(gtsummary)
library(tidyverse)
library("gplots")
library(ggpattern)
library(yaml)
library(rmarkdown)
library(purrr)
library(patchwork)
library(ggVennDiagram)




eq <- function(x,y) {
  m <- lm(y ~ x)
  a = paste0("Intercept = ",format(coef(m)[1], digits = 2))
  b = paste0("Slope = ",format(coef(m)[2], digits = 2))
  return(paste0(a, ", ", b))
}
